### ISSUE TITLE
Place close button on description

### ISSUE THREAD

**Issue by DanielApt** [SideshowJS/Sideshow#15]
Our demographic has very large viewports, and as a result we've noticed the *Close button* is overlooked.

We'd like to have the option to display the close button on the step itself. This is also common practice with the other guides I've seen. Something similar to the below screenshot:

![screen shot 2015-03-23 at 10 43 04](https://cloud.githubusercontent.com/assets/52545/6778286/6b0a76f4-d149-11e4-9bd8-27359d7bf2bf.png)

**Comment by AlbertoMonteiro** [comment]
Where close button will appear in the list of tutorials?

**Comment by DanielApt** [comment]
Good question, in our current situation we're not using the list of tutorials. 

We should still address this though:
Setting it on the same line as *Available Tutorials* would seem best suited.

**Comment by DanielApt** [comment]
This is the look I got going for the step right now.

![screen shot 2015-03-23 at 14 04 37](https://cloud.githubusercontent.com/assets/52545/6781464/da3eb49c-d165-11e4-955d-832f4c218ab5.png)

**Comment by AlbertoMonteiro** [comment]
Nicely done!!

**Comment by DanielApt** [comment]
Thanks. I'm working on it on the [`close-btn` branch](https://github.com/SideshowJS/Sideshow/tree/close-btn), so would love to have some feedback.

Especially the main question I have is what property to use. I'm currently using `SS.config.closePosition`, with valid values being `bottom-right` or `step`.

From past experience we know that items in the bottom-right are most overlooked, esp. on large displays. It might be useful to expand this position property to allow other values like `top-left`, `top-right` and `bottom-left`.

As said though, I'm happy to hear other people's thoughts.

**Comment by alcidesqueiroz** [comment]
Though here in our company we didn't have this specific issue (to put the close button inside the description box), I consider this enhancement absolutely valid. My only suggestion is to change the acceptable values for this property to `"description-box"` and `"screen-corner"`, and the property name itself to `closeButtonPosition`. What do you think?

**Comment by DanielApt** [comment]
Yeah sounds good, I'll make sure to update that once I have the chance.

**Comment by DanielApt** [comment]
Just pushed current work to develop.

**Comment by alcidesqueiroz** [comment]
Great work!

**Comment by peteallen** [comment]
We are looking for this feature as well. Is this still being worked on, or is it ready to be released?

**Comment by DanielApt** [comment]
Hi @peteallen,

Sorry I've had to slow down a bit on the dev work, while an internal project has taken prescedence. I hope to get a release out by the end of this month.

We do have a working version, but it's not been thoroughly tested for a release. It currently lives on the [develop branch](https://github.com/SideshowJS/Sideshow/tree/develop) if it's urgent.

**Comment by alcidesqueiroz** [comment]
@peteallen, as @DanielApt said, this feature is already done, and it will be released in our next official release. Coincidentally, Daniel and I are working on internal projects for the companies that each one of us work for. But, as soon as we can, this will be ready for production. If you *really need* this urgently, you can get the development version by using directly the [distr folder in the develop branch](https://github.com/SideshowJS/Sideshow/tree/develop/distr), since we do not pack develop versions. 

Cheers.

**Comment by alcidesqueiroz** [comment]
@DanielApt Now the close button also appears inside the wizard menu when its position is `'description-box'`. The feature is complete. I'm closing this issue. **=]**

**Comment by DanielApt** [comment]
Great work, I was worried how to place the button, but it actually works fine imho!
