### ISSUE TITLE
Skipped step still calls beforeListener

### ISSUE THREAD

**Issue by DanielApt** [SideshowJS/Sideshow#17]
Not sure if this is intentional, so maybe I can explain my current situation:

I want to skip a step if the nav is open.

If the nav is closed, I want to toggle the nav, before proceeding.

```js
{
    skipIf: function () {
        // returns true if the nav is open
    },
    title: 'Nav',
    text: 'Lorem ipsum'
    listeners: {
        beforeStep: function () {
            // toggles the nav
        }
    },
    completingConditions: [
        function () {
            // returns if the nav is open
        }
    ]
}
```

The problem here is that I'm expecting the skipped step not to call its `beforeStep` handler. Was there a specific reason for always calling the `beforeStep` handler? I'm happy to hear your thoughts @alcidesqueiroz

**Comment by alcidesqueiroz** [comment]
@DanielApt indeed, there's no reason for giving a higher precedence to beforeStep event than the skipIf evaluator. I made this change and pushed to develop: bc5f9ef.
