### ISSUE TITLE
New funcionality about positions of sideshow-subject-arrow

### ISSUE THREAD

**Issue by karnak25** [SideshowJS/Sideshow#4]
That will be great if the sideshow-subject-arrow could be positioned per step on the top, left, right or bottom (because in some pages with elements on the top, the arrow doesnt appaears)

**Comment by DanielApt** [comment]
You can now position the arrow by using the `arrowPosition` property in a step.

See release [v0.4.3](https://github.com/SideshowJS/Sideshow/releases/tag/v0.4.3-taxi-driver)
